#!/usr/bin/env bash

# Set the source audio player here.
# Players supporting the MPRIS spec are supported.
# Examples: spotify, vlc, chrome, mpv and others.
# Use `playerctld` to always detect the latest player.
# See more here: https://github.com/altdesktop/playerctl/#selecting-players-to-control
PLAYER="spotify"

PLAYERCTL_STATUS=$(playerctl --player=$PLAYER status 2>/dev/null)
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
  STATUS=$PLAYERCTL_STATUS
else
  STATUS=""
fi

_format() {
  playerctl -p $PLAYER metadata -f "%{T3}%{F#7edd8a}%{T- F-} {{ trunc(artist, 25) }} - {{ trunc(title, 25) }}"
}

if [ "$1" == "--status" ]; then
  echo "$STATUS"
else
  if [ "$STATUS" = "Playing" ]; then
    PLAYPAUSE_ICON=""
    _format
  elif [ "$STATUS" = "Paused" ]; then
    PLAYPAUSE_ICON=""
    _format
  else
    echo ""
  fi
fi
